version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mediway-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediwaydb
      MYSQL_USER: mediway
      MYSQL_PASSWORD: mediway123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - mediway-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mediway-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mediwaydb
      SPRING_DATASOURCE_USERNAME: mediway
      SPRING_DATASOURCE_PASSWORD: mediway123
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mediway-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mediway-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mediway-network

volumes:
  mysql_data:
    driver: local

networks:
  mediway-network:
    driver: bridge